apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: hapi
  name: hapi
spec:
  ports:
  - name: "9090"
    port: 9090
    targetPort: 9090
  selector:
    io.kompose.service: hapi
